  export const Data = [
    { 
    "first_name":"Naina Singh",
    "avatar":"https://reqres.in/img/faces/2-image.jpg",
    "Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
    "postImg":"https://media.istockphoto.com/photos/new-year-party-picture-id497317250?k=20&m=497317250&s=612x612&w=0&h=pQIM9f1iyRZXRZq1Qw5gXwwRaWQb4PCZCl8ngLSGl94=",
    "comment":90,
},
{ 
"first_name":"Pakrati Sathe",
"avatar":"https://reqres.in/img/faces/3-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeYZFx4D_f5xhh4Up-MhF2BxmYQPINdzSH9w&usqp=CAU",
"comment":121,
},
{ 
"first_name":"Sanjay Sharma", 
"avatar":"https://reqres.in/img/faces/4-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSL0QFN6a-s_VpVGCp56TaV-uAewmsnfKzLOw&usqp=CAU",
"comment":12,
},
{ 
"first_name":"Rahul kumar",
"avatar":"https://reqres.in/img/faces/6-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt_WKvYC4yppa51VoajfFwIU6dw24NlacsmA&usqp=CAU",
"comment":55,
},
{ 
"first_name": "Namrata Patil",
"avatar":"https://reqres.in/img/faces/7-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHo4jgY1ZeqbV3mO79cjzfTfDQtTR46kpCRv5cXbtyMd8MQuMv3Tvnw8dVd4SeqdRNTuo&usqp=CAU",
"comment":80,
},
  
{ 
"first_name":"George Bluth",
"avatar":"https://reqres.in/img/faces/8-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJsHVBKWgfjymV62umFn7Jbdj-yvUDkeQoIg&usqp=CAU",
"comment":78,
},
{ 
"first_name":"Anuj Kumar",
"avatar":"https://reqres.in/img/faces/9-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWL2arEHRvgHFIPIMobNgt_PeZJWZyQffOLw&usqp=CAU",
"comment":67,
},
{ 
"first_name":"Surya Bhatt",
"avatar":"https://reqres.in/img/faces/10-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKxCG93cKU5sWlPPPqSDr5Kwb8WBUkb6OAVg&usqp=CAU",
"comment":78,
},
{"id":1, 
"first_name":"Tanaya Khatri",
"avatar":"https://reqres.in/img/faces/11-imhttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4Ug2A13ZsN5d1ckoqb3m7LMPDK-DvJuzCIw&usqp=CAUage.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://www.mydomaine.com/thmb/URibDddhjkgdWb_3nDwiqjbbtzw=/500x0/filters:no_upscale():max_bytes(150000):strip_icc():gifv()/cdn.cliqueinc.com__cache__posts__271670__fun-things-to-do-at-a-party-271670-1541458784010-main.700x0c-832a9484444b4e2babc07765847ed81d.jpg",
"comment":45,
},
{"id":1, 
"first_name":"sanskuti Pandey",
"avatar":"https://reqres.in/img/faces/12-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyIY8fcuWMP-INIb-6aohWuDMJwp_FcIlMgg&usqp=CAU",
"comment":132,
},
{ 
"first_name":"Vishal Singh",
"avatar":"https://reqres.in/img/faces/9-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":67,
},
{ 
"first_name":"Ankit Varma",
"avatar":"https://reqres.in/img/faces/1-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://i.pinimg.com/550x/9f/3e/b7/9f3eb72e62ea26674373250a835da3b9.jpg",
"comment":300,
},
{  
"first_name":"Sneha Patil",
"avatar":"https://reqres.in/img/faces/7-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":41,
},
{  
"first_name":"Subhash Sahoo",
"avatar":"https://reqres.in/img/faces/9-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMAhjaB-gXNUc-LpSkYhwD8g7sgnXl5OkKNA&usqp=CAU",
"comment":86,
},
{ 
"first_name":"Ram Kumar",
"avatar":"https://reqres.in/img/faces/4-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":57,
},
{ 
"first_name":"Rakesh Kumar",
"avatar":"https://reqres.in/img/faces/4-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":90,
},
{ 
"first_name":"Poja devi",
"avatar":"https://reqres.in/img/faces/7-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNgx2oyp0QG5MC7bSH7SMHrMrM86F_roQcsA&usqp=CAU",
"comment":78,
},
{  
"first_name":"Naman jaiswal",
"avatar":"https://reqres.in/img/faces/6-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRd8fv5U3Y5yPp0841gdeEAYqZRIOHNtHRgDQ&usqp=CAU",
"comment":89,
},
{ 
"first_name":"Ranjeet Yadav",
"avatar":"https://reqres.in/img/faces/1-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"https://www.parents.com/thmb/ZqekDDy3Wq1kGHCs232l7zI_11w=/1600x1200/smart/filters:no_upscale()/monkey_business_images_9-ebeecdb09ee1443f98c707f1c95f2b8c.jpg",
"comment":90,
},
{ 
"first_name":"Pratiksha ",
"avatar":"https://reqres.in/img/faces/2-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":67,
},
{ 
"first_name":"Priyanka Singh",
"avatar":"https://reqres.in/img/faces/3-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":67,
},
{ 
"first_name":"Suneel Sukla",
"avatar":"https://reqres.in/img/faces/8-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":76,
},
{ 
"first_name":"Narendra Singh",
 "avatar":"https://reqres.in/img/faces/5-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":54,
},
{ 
"first_name":"Bhopendra Singh",
"avatar":"https://reqres.in/img/faces/8-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":84,
},
{ 
"first_name":"tannu devi",
"avatar":"https://reqres.in/img/faces/3-image.jpg",
"Post":"est rerum tempore vitae sequi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla",
"postImg":"",
"comment":78,
}]